/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author tm325716
 */
public class FrameChiffres extends javax.swing.JFrame { 
    /**
     * Creates new form frameChiffres
     */
    public FrameChiffres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Chiffres = new javax.swing.JPanel();
        Chiffre0 = new javax.swing.JButton();
        Chiffre1 = new javax.swing.JButton();
        Chiffre2 = new javax.swing.JButton();
        Chiffre3 = new javax.swing.JButton();
        Chiffre4 = new javax.swing.JButton();
        Chiffre5 = new javax.swing.JButton();
        Chiffre6 = new javax.swing.JButton();
        Chiffre7 = new javax.swing.JButton();
        Chiffre8 = new javax.swing.JButton();
        Chiffre9 = new javax.swing.JButton();
        Affichage = new javax.swing.JPanel();
        Message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setText("Apprenez à écrire les chiffres !");
        Titre.add(jLabel1);

        getContentPane().add(Titre, java.awt.BorderLayout.NORTH);

        Chiffres.setLayout(new java.awt.GridLayout(10, 1));

        Chiffre0.setText("0");
        Chiffre0.setPreferredSize(new java.awt.Dimension(100, 500));
        Chiffre0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre0ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre0);

        Chiffre1.setText("1");
        Chiffre1.setPreferredSize(new java.awt.Dimension(10, 20));
        Chiffre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre1ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre1);

        Chiffre2.setText("2");
        Chiffre2.setPreferredSize(new java.awt.Dimension(10, 20));
        Chiffre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre2ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre2);

        Chiffre3.setText("3");
        Chiffre3.setPreferredSize(new java.awt.Dimension(10, 20));
        Chiffre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre3ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre3);

        Chiffre4.setText("4");
        Chiffre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre4ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre4);

        Chiffre5.setText("5");
        Chiffre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre5ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre5);

        Chiffre6.setText("6");
        Chiffre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre6ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre6);

        Chiffre7.setText("7");
        Chiffre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre7ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre7);

        Chiffre8.setText("8");
        Chiffre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre8ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre8);

        Chiffre9.setText("9");
        Chiffre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chiffre9ActionPerformed(evt);
            }
        });
        Chiffres.add(Chiffre9);

        getContentPane().add(Chiffres, java.awt.BorderLayout.EAST);

        Affichage.setLayout(new java.awt.GridLayout(1, 1));

        Message.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Message.setText("Cliquez sur un bouton !");
        Affichage.add(Message);

        getContentPane().add(Affichage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Chiffre0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre0ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.green);
        Message.setText("zéro");
    }//GEN-LAST:event_Chiffre0ActionPerformed

    private void Chiffre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre1ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.red);
        Message.setText("un");
    }//GEN-LAST:event_Chiffre1ActionPerformed

    private void Chiffre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre2ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.blue);
        Message.setText("deux");
    }//GEN-LAST:event_Chiffre2ActionPerformed

    private void Chiffre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre3ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.yellow);
        Message.setText("trois");
    }//GEN-LAST:event_Chiffre3ActionPerformed

    private void Chiffre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre4ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.orange);
        Message.setText("quatre");
    }//GEN-LAST:event_Chiffre4ActionPerformed

    private void Chiffre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre5ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.white);
        Message.setText("cinq");
    }//GEN-LAST:event_Chiffre5ActionPerformed

    private void Chiffre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre6ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.red);
        Message.setText("six");
    }//GEN-LAST:event_Chiffre6ActionPerformed

    private void Chiffre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre7ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.cyan);
        Message.setText("sept");
    }//GEN-LAST:event_Chiffre7ActionPerformed

    private void Chiffre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre8ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.white);
        Message.setText("huit");
    }//GEN-LAST:event_Chiffre8ActionPerformed

    private void Chiffre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chiffre9ActionPerformed
        // TODO add your handling code here:
        Message.setForeground(Color.pink);
        Message.setText("neuf");
    }//GEN-LAST:event_Chiffre9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameChiffres  lc=new FrameChiffres();
                lc.setSize(1000,800);
                lc.setTitle("Les Chiffres");
                lc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Affichage;
    private javax.swing.JButton Chiffre0;
    private javax.swing.JButton Chiffre1;
    private javax.swing.JButton Chiffre2;
    private javax.swing.JButton Chiffre3;
    private javax.swing.JButton Chiffre4;
    private javax.swing.JButton Chiffre5;
    private javax.swing.JButton Chiffre6;
    private javax.swing.JButton Chiffre7;
    private javax.swing.JButton Chiffre8;
    private javax.swing.JButton Chiffre9;
    private javax.swing.JPanel Chiffres;
    private javax.swing.JLabel Message;
    private javax.swing.JPanel Titre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
